apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.tycho_api_service_name }}
  labels:
    {{- include "tycho-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ip_none }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "tycho-api.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 8099
    protocol: TCP
    targetPort: 8099
